---
# defaults file for ansible-role-consul-install

consul_version: latest
consul_arch: linux_amd64
checkpoint_url: "https://checkpoint-api.hashicorp.com/v1/check/consul"
consul_dependencies:
  - unzip
consul_bin_path: "/usr/bin"
consul_path: "/var/lib/consul"
consul_conf: "/etc/consul/consul_agent.hcl"
consul_datacenter: "dc1"
consul_base_ip: "10.1.42."
consul_user: "consul"
consul_uid: "8501"
consul_group: "consul"
consul_gid: "8501"
consul_service: "consul"

