---

- name: Install & configure HAProxy & Keepalived
  hosts: haproxy
  become: yes
  gather_facts: yes

  roles:
    - { role: ansible-role-haproxy-remove, tags: [ 'never', 'remove' ] }
    - { role: ansible-role-haproxy-install, tags: install }
    - { role: ansible-role-haproxy-start, tags: [ 'never', 'start' ] }
    - { role: ansible-role-haproxy-stop, tags: [ 'never', 'stop' ] }
    - { role: ansible-role-haproxy-reload, tags: [ 'never', 'reload' ] }

