---

- name: Install & configure Hashicorp Consul cluster + Vault + HAProxy
  hosts: all
  gather_facts: no

- import_playbook: consul.yml
- import_playbook: vault.yml
- import_playbook: haproxy.yml

